"""Admin-facing join-token management.

The public onboarding endpoint lives at ``GET /api/join/{token}`` (see
``routers/join.py``) — it's unauthenticated and single-use. This router
is the other half: the admin-only surface for minting and revoking the
tokens that end up in those invite URLs.

Scope: admin-only. Any authenticated admin can see, mint, and revoke any
join token — they're short-lived invites, not per-user credentials, so
there's no "my tokens" view like there is for PATs.

Why it lives under ``/admin/api``: it's an operator tool (onboarding a
new end-user device), not an account-level feature.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from sqlmodel import select

from ..deps import AdminUser, SessionDep
from ..models.audit_log import AuditAction, AuditLog
from ..models.join_token import JoinToken
from ..security import utcnow_naive

router = APIRouter(prefix="/admin/api/join-tokens", tags=["admin:join-tokens"])


# ─── Schemas ────────────────────────────────────────────────────────────────


class JoinTokenOut(BaseModel):
    """Join-token row as the admin UI sees it.

    Unlike PATs we return the plaintext ``token`` here: admins need to
    copy it into the onboarding URL they share with the end user, and
    it's already single-use + short-lived so the leak radius is tiny.
    Anyone who sees the admin API sees /api/join/:token traffic anyway.
    """

    id: int
    token: str
    label: str | None
    created_by_user_id: int | None
    created_at: datetime
    expires_at: datetime | None
    used_at: datetime | None
    revoked: bool
    # Derived for the UI so the list view doesn't re-compute it client-side.
    status: str  # "active" | "used" | "expired" | "revoked"


class JoinTokenCreate(BaseModel):
    label: str | None = Field(default=None, max_length=128)
    # Minutes from now. None = never expires. Cap at 30 days — these are
    # invites, not long-lived credentials. Longer than that is almost
    # certainly a mistake.
    expires_in_minutes: int | None = Field(default=None, ge=1, le=30 * 24 * 60)


# ─── Helpers ────────────────────────────────────────────────────────────────


def _status(t: JoinToken, now: datetime) -> str:
    # Order matters: revoked wins over used wins over expired. A row that
    # was used and then revoked should still report "revoked" so the admin
    # can tell they did the revoke (forensics).
    if t.revoked:
        return "revoked"
    if t.used_at is not None:
        return "used"
    if t.expires_at is not None and t.expires_at < now:
        return "expired"
    return "active"


def _to_out(t: JoinToken, now: datetime) -> JoinTokenOut:
    return JoinTokenOut(
        id=t.id,  # type: ignore[arg-type]
        token=t.token,
        label=t.label,
        created_by_user_id=t.created_by_user_id,
        created_at=t.created_at,
        expires_at=t.expires_at,
        used_at=t.used_at,
        revoked=t.revoked,
        status=_status(t, now),
    )


# ─── Routes ─────────────────────────────────────────────────────────────────


@router.post("", response_model=JoinTokenOut, status_code=status.HTTP_201_CREATED)
def create_join_token(
    body: JoinTokenCreate,
    admin: AdminUser,
    session: SessionDep,
) -> JoinTokenOut:
    now = utcnow_naive()
    expires_at: datetime | None = None
    if body.expires_in_minutes is not None:
        expires_at = now + timedelta(minutes=body.expires_in_minutes)

    row = JoinToken(
        label=body.label,
        created_by_user_id=admin.id,
        expires_at=expires_at,
        # token is generated by the model default
    )
    session.add(row)
    session.commit()
    session.refresh(row)

    session.add(
        AuditLog(
            action=AuditAction.JOIN_TOKEN_CREATED,
            actor_user_id=admin.id,
            payload=f"id={row.id} label={(row.label or '')[:64]}",
        )
    )
    session.commit()

    return _to_out(row, now)


@router.get("", response_model=list[JoinTokenOut])
def list_join_tokens(
    admin: AdminUser,  # noqa: ARG001 — require admin
    session: SessionDep,
) -> list[JoinTokenOut]:
    now = utcnow_naive()
    rows = session.exec(
        select(JoinToken).order_by(JoinToken.created_at.desc())  # type: ignore[attr-defined]
    ).all()
    return [_to_out(r, now) for r in rows]


@router.delete("/{token_id}", status_code=status.HTTP_204_NO_CONTENT)
def revoke_join_token(
    token_id: int,
    admin: AdminUser,
    session: SessionDep,
) -> None:
    row = session.get(JoinToken, token_id)
    if not row:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Join token not found")
    if row.revoked:
        # Idempotent — no audit entry the second time, nothing changed.
        return
    row.revoked = True
    session.add(row)
    session.add(
        AuditLog(
            action=AuditAction.JOIN_TOKEN_REVOKED,
            actor_user_id=admin.id,
            payload=f"id={row.id} label={(row.label or '')[:64]}",
        )
    )
    session.commit()
