"""Admin-facing join-token management.

The public onboarding endpoint lives at ``GET /api/join/{token}`` (see
``routers/join.py``) — it's unauthenticated and single-use. This router
is the other half: the admin-only surface for minting and revoking the
tokens that end up in those invite URLs.

Scope: admin-only. Any authenticated admin can see, mint, and revoke any
join token — they're short-lived invites, not per-user credentials, so
there's no "my tokens" view like there is for PATs.

Why it lives under ``/admin/api``: it's an operator tool (onboarding a
new end-user device), not an account-level feature.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from sqlmodel import select

from ..deps import AdminUser, SessionDep
from ..models.audit_log import AuditAction, AuditLog
from ..models.join_token import JoinToken
from ..security import utcnow_naive

router = APIRouter(prefix="/admin/api/join-tokens", tags=["admin:join-tokens"])


# ─── Schemas ────────────────────────────────────────────────────────────────


class JoinTokenOut(BaseModel):
    """Join-token metadata — list/read view.

    Matches the PAT redaction pattern: ``token_prefix`` for identification
    in lists, never the full plaintext. Admins get the full token back
    ONCE on create (see :class:`JoinTokenCreateOut`); if they lose it,
    they revoke and mint a new one. Keeps the admin-side leak radius
    consistent with /api/auth/tokens.
    """

    id: int
    token_prefix: str  # first 8 chars — enough to identify, not to redeem
    label: str | None
    created_by_user_id: int | None
    created_at: datetime
    expires_at: datetime | None
    used_at: datetime | None
    revoked: bool
    # Derived for the UI so the list view doesn't re-compute it client-side.
    status: str  # "active" | "used" | "expired" | "revoked"


class JoinTokenCreateOut(JoinTokenOut):
    """Returned ONCE on create. The plaintext ``token`` field is never
    available again — lose it, revoke and mint a new one."""

    token: str


class JoinTokenCreate(BaseModel):
    label: str | None = Field(default=None, max_length=128)
    # Minutes from now. None = never expires. Cap at 30 days — these are
    # invites, not long-lived credentials. Longer than that is almost
    # certainly a mistake.
    expires_in_minutes: int | None = Field(default=None, ge=1, le=30 * 24 * 60)


# ─── Helpers ────────────────────────────────────────────────────────────────


def _status(t: JoinToken, now: datetime) -> str:
    # Order matters: revoked wins over used wins over expired. A row that
    # was used and then revoked should still report "revoked" so the admin
    # can tell they did the revoke (forensics).
    if t.revoked:
        return "revoked"
    if t.used_at is not None:
        return "used"
    if t.expires_at is not None and t.expires_at < now:
        return "expired"
    return "active"


def _to_out(t: JoinToken, now: datetime) -> JoinTokenOut:
    return JoinTokenOut(
        id=t.id,  # type: ignore[arg-type]
        token_prefix=t.token[:8],
        label=t.label,
        created_by_user_id=t.created_by_user_id,
        created_at=t.created_at,
        expires_at=t.expires_at,
        used_at=t.used_at,
        revoked=t.revoked,
        status=_status(t, now),
    )


def _to_create_out(t: JoinToken, now: datetime) -> JoinTokenCreateOut:
    """Create-time response — includes the plaintext ``token`` ONCE.

    Mirrors the PAT pattern in ``routers/api_tokens.py``: full secret is
    returned exactly once on create, never again on list/read. If the
    admin loses it, they revoke and mint a new one.
    """
    return JoinTokenCreateOut(
        id=t.id,  # type: ignore[arg-type]
        token=t.token,
        token_prefix=t.token[:8],
        label=t.label,
        created_by_user_id=t.created_by_user_id,
        created_at=t.created_at,
        expires_at=t.expires_at,
        used_at=t.used_at,
        revoked=t.revoked,
        status=_status(t, now),
    )


# ─── Routes ─────────────────────────────────────────────────────────────────


@router.post("", response_model=JoinTokenCreateOut, status_code=status.HTTP_201_CREATED)
def create_join_token(
    body: JoinTokenCreate,
    admin: AdminUser,
    session: SessionDep,
) -> JoinTokenCreateOut:
    now = utcnow_naive()
    expires_at: datetime | None = None
    if body.expires_in_minutes is not None:
        expires_at = now + timedelta(minutes=body.expires_in_minutes)

    row = JoinToken(
        label=body.label,
        created_by_user_id=admin.id,
        expires_at=expires_at,
        # token is generated by the model default
    )
    session.add(row)
    session.commit()
    session.refresh(row)

    session.add(
        AuditLog(
            action=AuditAction.JOIN_TOKEN_CREATED,
            actor_user_id=admin.id,
            payload=f"id={row.id} label={(row.label or '')[:64]}",
        )
    )
    session.commit()

    return _to_create_out(row, now)


@router.get("", response_model=list[JoinTokenOut])
def list_join_tokens(
    admin: AdminUser,  # noqa: ARG001 — require admin
    session: SessionDep,
    include_revoked: bool = False,
) -> list[JoinTokenOut]:
    """List join tokens.

    Default hides revoked rows — the admin asked for "revoke = out of
    sight" as the common case. The full history (including revoked) is
    still accessible via `?include_revoked=true` for audit/forensics,
    and every revoke+delete is stamped in `/admin/api/logs` anyway.
    """
    now = utcnow_naive()
    stmt = select(JoinToken)
    if not include_revoked:
        # `revoked` is a non-null bool column; explicit False keeps the
        # filter readable in the query log.
        stmt = stmt.where(JoinToken.revoked == False)  # noqa: E712
    stmt = stmt.order_by(JoinToken.created_at.desc())  # type: ignore[attr-defined]
    rows = session.exec(stmt).all()
    return [_to_out(r, now) for r in rows]


@router.delete("/{token_id}", status_code=status.HTTP_204_NO_CONTENT)
def revoke_or_delete_join_token(
    token_id: int,
    admin: AdminUser,
    session: SessionDep,
    hard: bool = False,
) -> None:
    """Revoke (soft, default) or permanently delete a join token.

    * No flag → revoke: sets `revoked=true`, audit `JOIN_TOKEN_REVOKED`.
      Idempotent (already-revoked is a 204 no-op with no second audit).
    * `?hard=true` → delete: removes the row. Audit `JOIN_TOKEN_DELETED`
      captures the metadata so the fact-of-deletion is preserved even
      though the row isn't.
    """
    row = session.get(JoinToken, token_id)
    if not row:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Join token not found")

    if hard:
        # Capture the identifying bits BEFORE the delete so the audit
        # payload doesn't reach into a flushed object.
        payload = f"id={row.id} prefix={row.token[:8]} label={(row.label or '')[:64]}"
        session.delete(row)
        session.add(AuditLog(
            action=AuditAction.JOIN_TOKEN_DELETED,
            actor_user_id=admin.id,
            payload=payload,
        ))
        session.commit()
        return

    if row.revoked:
        # Idempotent — no audit entry the second time, nothing changed.
        return
    row.revoked = True
    session.add(row)
    session.add(
        AuditLog(
            action=AuditAction.JOIN_TOKEN_REVOKED,
            actor_user_id=admin.id,
            payload=f"id={row.id} label={(row.label or '')[:64]}",
        )
    )
    session.commit()


# ─── Bulk ops ──────────────────────────────────────────────────────────────


class BulkJoinTokensBody(BaseModel):
    """Bulk revoke/delete of join tokens.

    `action` mirrors the per-row surface:
      * ``revoke`` → set revoked=true. Skips rows already revoked with
        reason ``already_revoked``.
      * ``delete`` → hard delete regardless of revoke state. Fact-of-
        deletion stamped in audit per row.
    """
    action: str = Field(pattern="^(revoke|delete)$")
    ids: list[int] = Field(min_length=1, max_length=200)


class BulkJoinTokensResult(BaseModel):
    action: str
    affected: int
    skipped: list[dict]  # {id, reason}


@router.post("/bulk", response_model=BulkJoinTokensResult)
def bulk_join_tokens(
    body: BulkJoinTokensBody,
    session: SessionDep,
    admin: AdminUser,
) -> BulkJoinTokensResult:
    """Apply revoke or delete to a batch of join tokens in one transaction.

    Errors per row (not_found, already_revoked) collected into
    ``skipped`` rather than aborting the batch — matches the Users bulk
    shape so the UI handling is identical.
    """
    ids = list(dict.fromkeys(body.ids))
    rows = session.exec(
        select(JoinToken).where(JoinToken.id.in_(ids))  # type: ignore[attr-defined]
    ).all()
    found = {r.id: r for r in rows}

    skipped: list[dict] = []
    affected = 0

    def skip(rid: int, reason: str) -> None:
        skipped.append({"id": rid, "reason": reason})

    for rid in ids:
        row = found.get(rid)
        if row is None:
            skip(rid, "not_found")
            continue

        if body.action == "revoke":
            if row.revoked:
                skip(rid, "already_revoked")
                continue
            row.revoked = True
            session.add(row)
            session.add(AuditLog(
                action=AuditAction.JOIN_TOKEN_REVOKED,
                actor_user_id=admin.id,
                payload=f"id={row.id} label={(row.label or '')[:64]}",
            ))
            affected += 1

        elif body.action == "delete":
            payload = f"id={row.id} prefix={row.token[:8]} label={(row.label or '')[:64]}"
            session.delete(row)
            session.add(AuditLog(
                action=AuditAction.JOIN_TOKEN_DELETED,
                actor_user_id=admin.id,
                payload=payload,
            ))
            affected += 1

    session.commit()
    return BulkJoinTokensResult(
        action=body.action, affected=affected, skipped=skipped,
    )
